//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compdfkit_Tools.Strings.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compdfkit_Tools.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New File.
        /// </summary>
        internal static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document.
        /// </summary>
        internal static string Button_Open {
            get {
                return ResourceManager.GetString("Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Caption_Warning {
            get {
                return ResourceManager.GetString("Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        internal static string Chk_Tile {
            get {
                return ResourceManager.GetString("Chk_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Flattened PDF.
        /// </summary>
        internal static string FileMenu_Flatten {
            get {
                return ResourceManager.GetString("FileMenu_Flatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document.
        /// </summary>
        internal static string FileMenu_Open {
            get {
                return ResourceManager.GetString("FileMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FileMenu_Save {
            get {
                return ResourceManager.GetString("FileMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string FileMenu_SaveAs {
            get {
                return ResourceManager.GetString("FileMenu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string Func_Annotations {
            get {
                return ResourceManager.GetString("Func_Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string Func_Compress {
            get {
                return ResourceManager.GetString("Func_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Editor.
        /// </summary>
        internal static string Func_ContentEditor {
            get {
                return ResourceManager.GetString("Func_ContentEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        internal static string Func_Conversion {
            get {
                return ResourceManager.GetString("Func_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Documents.
        /// </summary>
        internal static string Func_DocCompare {
            get {
                return ResourceManager.GetString("Func_DocCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Editor.
        /// </summary>
        internal static string Func_DocEditor {
            get {
                return ResourceManager.GetString("Func_DocEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string Func_Forms {
            get {
                return ResourceManager.GetString("Func_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string Func_Measurement {
            get {
                return ResourceManager.GetString("Func_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaction.
        /// </summary>
        internal static string Func_Redaction {
            get {
                return ResourceManager.GetString("Func_Redaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Func_Security {
            get {
                return ResourceManager.GetString("Func_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures.
        /// </summary>
        internal static string Func_Signatures {
            get {
                return ResourceManager.GetString("Func_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        internal static string Func_Viewer {
            get {
                return ResourceManager.GetString("Func_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        internal static string Func_Watermark {
            get {
                return ResourceManager.GetString("Func_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotate and markup PDFs with notes, links, free text, line, square, arrow, circle, highlight, underline, squiggly, strikeout, stamps, ink, signature, sound, etc. Allow to create, delete, edit, import, export, and flatten PDF annotations. .
        /// </summary>
        internal static string FuncDetail_Annotations {
            get {
                return ResourceManager.GetString("FuncDetail_Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize your PDF file with compression, reducing PDF document size with no or minimum visual quality loss..
        /// </summary>
        internal static string FuncDetail_Compress {
            get {
                return ResourceManager.GetString("FuncDetail_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the text and images with ComPDFKit Content Editor. Give you the freedom to adjust the size, position, style, font, etc..
        /// </summary>
        internal static string FuncDetail_ContentEditor {
            get {
                return ResourceManager.GetString("FuncDetail_ContentEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert PDF to PDF/A. ComPDFKit also supports converting PDF to/from Word, Excel, PPT, PNG, JPG, HTML, TXT, CSV, RTF, etc..
        /// </summary>
        internal static string FuncDetail_Conversion {
            get {
                return ResourceManager.GetString("FuncDetail_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to compare PDF files and design drawings with content comparison and overlay comparison - support setting file color to compare and choose how you want to show the differences..
        /// </summary>
        internal static string FuncDetail_DocCompare {
            get {
                return ResourceManager.GetString("FuncDetail_DocCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process PDF pages and files. Add, insert, replace, extract, reverse, move, copy, paste, rotate, delete, crop, scale, etc..
        /// </summary>
        internal static string FuncDetail_DocEditor {
            get {
                return ResourceManager.GetString("FuncDetail_DocEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, delete, edit, fill, flatten, import, and export forms. Support a wide array of PDF form fields including text field, check box, radio button, list box, combo button, push button, and signatures..
        /// </summary>
        internal static string FuncDetail_Forms {
            get {
                return ResourceManager.GetString("FuncDetail_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and edit distance, perimeter, area, angle, diameter, radius, and volume measurement annotations. Support changing the scale and precision of measurement annotations..
        /// </summary>
        internal static string FuncDetail_Measurement {
            get {
                return ResourceManager.GetString("FuncDetail_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use redaction to remove sensitive images, text, and vector graphics, that can&apos;t be recovered after applying the redaction. Support customizing redaction appearance and choosing an area or searching for specific text to redact..
        /// </summary>
        internal static string FuncDetail_Redaction {
            get {
                return ResourceManager.GetString("FuncDetail_Redaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure your documents using AES-128, AES-256, or RC4 encryption. Allow to encrypt, decrypt, and customize permissions, edit headers &amp; footers, background, Bates numbers, etc..
        /// </summary>
        internal static string FuncDetail_Security {
            get {
                return ResourceManager.GetString("FuncDetail_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign PDFs with digital signatures and electronic signatures. Choose the drawn, image, or typed signatures and sign files conveniently. Or sign with your digital ID securely..
        /// </summary>
        internal static string FuncDetail_Signatures {
            get {
                return ResourceManager.GetString("FuncDetail_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View PDFs with tools like display modes, navigation, display themes, scrolling, zooming,  text searching, text reflow, split viewer, etc..
        /// </summary>
        internal static string FuncDetail_Viewer {
            get {
                return ResourceManager.GetString("FuncDetail_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, insert, and remove text or image watermarks to brand your users&apos; work and discourage its unauthorized use..
        /// </summary>
        internal static string FuncDetail_Watermark {
            get {
                return ResourceManager.GetString("FuncDetail_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ComPDFKit.
        /// </summary>
        internal static string HelpMenu_About {
            get {
                return ResourceManager.GetString("HelpMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Sales.
        /// </summary>
        internal static string HelpMenu_Contact {
            get {
                return ResourceManager.GetString("HelpMenu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Your Developer Device ID.
        /// </summary>
        internal static string HelpMenu_DeviceID {
            get {
                return ResourceManager.GetString("HelpMenu_DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string HelpMenu_Privacy {
            get {
                return ResourceManager.GetString("HelpMenu_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Terms.
        /// </summary>
        internal static string HelpMenu_Service {
            get {
                return ResourceManager.GetString("HelpMenu_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        internal static string HelpMenu_Support {
            get {
                return ResourceManager.GetString("HelpMenu_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Resize.
        /// </summary>
        internal static string Menu_AutoSize {
            get {
                return ResourceManager.GetString("Menu_AutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string Menu_Crop {
            get {
                return ResourceManager.GetString("Menu_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Page Continuous.
        /// </summary>
        internal static string Menu_DoubleContinuous {
            get {
                return ResourceManager.GetString("Menu_DoubleContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Page.
        /// </summary>
        internal static string Menu_DoublePage {
            get {
                return ResourceManager.GetString("Menu_DoublePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip horizontal.
        /// </summary>
        internal static string Menu_HFlip {
            get {
                return ResourceManager.GetString("Menu_HFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Menu_Highlight {
            get {
                return ResourceManager.GetString("Menu_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Source Formatting Paste.
        /// </summary>
        internal static string Menu_MatchPaste {
            get {
                return ResourceManager.GetString("Menu_MatchPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Menu_Opacity {
            get {
                return ResourceManager.GetString("Menu_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Menu_Play {
            get {
                return ResourceManager.GetString("Menu_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        internal static string Menu_RealSize {
            get {
                return ResourceManager.GetString("Menu_RealSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Menu_Replace {
            get {
                return ResourceManager.GetString("Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Forms.
        /// </summary>
        internal static string Menu_Reset {
            get {
                return ResourceManager.GetString("Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Left.
        /// </summary>
        internal static string Menu_RotateLeft {
            get {
                return ResourceManager.GetString("Menu_RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Right.
        /// </summary>
        internal static string Menu_RotateRight {
            get {
                return ResourceManager.GetString("Menu_RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        internal static string Menu_Sign {
            get {
                return ResourceManager.GetString("Menu_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Page Continuous.
        /// </summary>
        internal static string Menu_SingleContinuous {
            get {
                return ResourceManager.GetString("Menu_SingleContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Page.
        /// </summary>
        internal static string Menu_SinglePage {
            get {
                return ResourceManager.GetString("Menu_SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squiggly.
        /// </summary>
        internal static string Menu_Squiggly {
            get {
                return ResourceManager.GetString("Menu_Squiggly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikeout.
        /// </summary>
        internal static string Menu_Strikeout {
            get {
                return ResourceManager.GetString("Menu_Strikeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Menu_Underline {
            get {
                return ResourceManager.GetString("Menu_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip vertical.
        /// </summary>
        internal static string Menu_VFlip {
            get {
                return ResourceManager.GetString("Menu_VFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string Menu_ZoomIn {
            get {
                return ResourceManager.GetString("Menu_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string Menu_ZoomOut {
            get {
                return ResourceManager.GetString("Menu_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3(11.69&quot;x 16.54&quot;).
        /// </summary>
        internal static string Option_A3 {
            get {
                return ResourceManager.GetString("Option_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4(8.27”x 11.69&quot;).
        /// </summary>
        internal static string Option_A4 {
            get {
                return ResourceManager.GetString("Option_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A5(5.83&quot;x 8.27&quot;).
        /// </summary>
        internal static string Option_A5 {
            get {
                return ResourceManager.GetString("Option_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pages.
        /// </summary>
        internal static string Option_AllPage {
            get {
                return ResourceManager.GetString("Option_AllPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom pages.
        /// </summary>
        internal static string Option_CustomPages {
            get {
                return ResourceManager.GetString("Option_CustomPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even pages only.
        /// </summary>
        internal static string Option_EvenPages {
            get {
                return ResourceManager.GetString("Option_EvenPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string Option_Landscape {
            get {
                return ResourceManager.GetString("Option_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd pages only.
        /// </summary>
        internal static string Option_OddPages {
            get {
                return ResourceManager.GetString("Option_OddPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string Option_Portrait {
            get {
                return ResourceManager.GetString("Option_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Property_Progress {
            get {
                return ResourceManager.GetString("Property_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Orientation.
        /// </summary>
        internal static string Subtitle_Orientation {
            get {
                return ResourceManager.GetString("Subtitle_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        internal static string Subtitle_PageSize {
            get {
                return ResourceManager.GetString("Subtitle_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseda.
        /// </summary>
        internal static string temp {
            get {
                return ResourceManager.GetString("temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load image failed. Please check if the image is corrupted..
        /// </summary>
        internal static string Text_ImageCorrupted {
            get {
                return ResourceManager.GetString("Text_ImageCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Text_Page {
            get {
                return ResourceManager.GetString("Text_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        internal static string Text_Tile {
            get {
                return ResourceManager.GetString("Text_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Encrypted!.
        /// </summary>
        internal static string Tip_Encrypted {
            get {
                return ResourceManager.GetString("Tip_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Tip_Password {
            get {
                return ResourceManager.GetString("Tip_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is with permission restrictions..
        /// </summary>
        internal static string Tip_Permission {
            get {
                return ResourceManager.GetString("Tip_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        internal static string Tip_WrongPassword {
            get {
                return ResourceManager.GetString("Tip_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Setting.
        /// </summary>
        internal static string Title_Display {
            get {
                return ResourceManager.GetString("Title_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        internal static string Title_DisplayMode {
            get {
                return ResourceManager.GetString("Title_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Title_Features {
            get {
                return ResourceManager.GetString("Title_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New File.
        /// </summary>
        internal static string Title_NewFile {
            get {
                return ResourceManager.GetString("Title_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Password.
        /// </summary>
        internal static string Title_Password {
            get {
                return ResourceManager.GetString("Title_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Title_Preview {
            get {
                return ResourceManager.GetString("Title_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Open &amp; Process.
        /// </summary>
        internal static string Title_QuickStart {
            get {
                return ResourceManager.GetString("Title_QuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split View.
        /// </summary>
        internal static string Title_SplitView {
            get {
                return ResourceManager.GetString("Title_SplitView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Title_Themes {
            get {
                return ResourceManager.GetString("Title_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Scrolling.
        /// </summary>
        internal static string Toggle_Continuous {
            get {
                return ResourceManager.GetString("Toggle_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Mode.
        /// </summary>
        internal static string Toggle_Crop {
            get {
                return ResourceManager.GetString("Toggle_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Mode.
        /// </summary>
        internal static string Tooltip_CoverMode {
            get {
                return ResourceManager.GetString("Tooltip_CoverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Tooltip_Dark {
            get {
                return ResourceManager.GetString("Tooltip_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Display.
        /// </summary>
        internal static string Tooltip_Display {
            get {
                return ResourceManager.GetString("Tooltip_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Info.
        /// </summary>
        internal static string Tooltip_DocInfo {
            get {
                return ResourceManager.GetString("Tooltip_DocInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Page.
        /// </summary>
        internal static string Tooltip_DoublePage {
            get {
                return ResourceManager.GetString("Tooltip_DoublePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Tooltip_Horizontal {
            get {
                return ResourceManager.GetString("Tooltip_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Tooltip_Light {
            get {
                return ResourceManager.GetString("Tooltip_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Tooltip_Next {
            get {
                return ResourceManager.GetString("Tooltip_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string Tooltip_Open {
            get {
                return ResourceManager.GetString("Tooltip_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string Tooltip_Panel {
            get {
                return ResourceManager.GetString("Tooltip_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Tooltip_Previous {
            get {
                return ResourceManager.GetString("Tooltip_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Tooltip_Prop {
            get {
                return ResourceManager.GetString("Tooltip_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Tooltip_Redo {
            get {
                return ResourceManager.GetString("Tooltip_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseda.
        /// </summary>
        internal static string Tooltip_Reseda {
            get {
                return ResourceManager.GetString("Tooltip_Reseda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Tooltip_Save {
            get {
                return ResourceManager.GetString("Tooltip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Tooltip_Search {
            get {
                return ResourceManager.GetString("Tooltip_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        internal static string Tooltip_Sepia {
            get {
                return ResourceManager.GetString("Tooltip_Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Page.
        /// </summary>
        internal static string Tooltip_SinglePage {
            get {
                return ResourceManager.GetString("Tooltip_SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Tooltip_Undo {
            get {
                return ResourceManager.GetString("Tooltip_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Tooltip_Vertical {
            get {
                return ResourceManager.GetString("Tooltip_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string Tooltip_ZoomIn {
            get {
                return ResourceManager.GetString("Tooltip_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string Tooltip_ZoomOut {
            get {
                return ResourceManager.GetString("Tooltip_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string Warn_Delete {
            get {
                return ResourceManager.GetString("Warn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is changed. Do you want to save the changes?.
        /// </summary>
        internal static string Warn_NotSave {
            get {
                return ResourceManager.GetString("Warn_NotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Page.
        /// </summary>
        internal static string Zoom_FitPage {
            get {
                return ResourceManager.GetString("Zoom_FitPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Width.
        /// </summary>
        internal static string Zoom_FitWidth {
            get {
                return ResourceManager.GetString("Zoom_FitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        internal static string Zoom_Real {
            get {
                return ResourceManager.GetString("Zoom_Real", resourceCulture);
            }
        }
    }
}
