//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compdfkit_Tools.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compdfkit_Tools.Strings.DocEditor", typeof(DocEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string Button_Extract {
            get {
                return ResourceManager.GetString("Button_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Button_Insert {
            get {
                return ResourceManager.GetString("Button_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File.
        /// </summary>
        internal static string Button_Select {
            get {
                return ResourceManager.GetString("Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 1,3-5,10.
        /// </summary>
        internal static string Holder_Custom {
            get {
                return ResourceManager.GetString("Holder_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string Option_After {
            get {
                return ResourceManager.GetString("Option_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string Option_Before {
            get {
                return ResourceManager.GetString("Option_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Page.
        /// </summary>
        internal static string Option_Blank {
            get {
                return ResourceManager.GetString("Option_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Blank Page.
        /// </summary>
        internal static string Option_Custom {
            get {
                return ResourceManager.GetString("Option_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page after extraction.
        /// </summary>
        internal static string Option_Delete {
            get {
                return ResourceManager.GetString("Option_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        internal static string Option_First {
            get {
                return ResourceManager.GetString("Option_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From PDF.
        /// </summary>
        internal static string Option_From {
            get {
                return ResourceManager.GetString("Option_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        internal static string Option_Last {
            get {
                return ResourceManager.GetString("Option_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Option_Page {
            get {
                return ResourceManager.GetString("Option_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each page in a separate file.
        /// </summary>
        internal static string Option_Separate {
            get {
                return ResourceManager.GetString("Option_Separate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pages.
        /// </summary>
        internal static string Range_All {
            get {
                return ResourceManager.GetString("Range_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Range.
        /// </summary>
        internal static string Range_Custom {
            get {
                return ResourceManager.GetString("Range_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even Pages Only.
        /// </summary>
        internal static string Range_Even {
            get {
                return ResourceManager.GetString("Range_Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd Pages Only.
        /// </summary>
        internal static string Range_Odd {
            get {
                return ResourceManager.GetString("Range_Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Range.
        /// </summary>
        internal static string Subtitle_Pages {
            get {
                return ResourceManager.GetString("Subtitle_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert To.
        /// </summary>
        internal static string Subtitle_Pos {
            get {
                return ResourceManager.GetString("Subtitle_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Range.
        /// </summary>
        internal static string Text_Range {
            get {
                return ResourceManager.GetString("Text_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete all pages. Please keep at least one page..
        /// </summary>
        internal static string Tip_AllPage {
            get {
                return ResourceManager.GetString("Tip_AllPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages selected. Please select one or more pages first to organize..
        /// </summary>
        internal static string Tip_NoPage {
            get {
                return ResourceManager.GetString("Tip_NoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string Title_Extract {
            get {
                return ResourceManager.GetString("Title_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Title_Insert {
            get {
                return ResourceManager.GetString("Title_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string Warn_Delete {
            get {
                return ResourceManager.GetString("Warn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected.
        /// </summary>
        internal static string Warn_NoFile {
            get {
                return ResourceManager.GetString("Warn_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page range or the page number is out of range..
        /// </summary>
        internal static string Warn_PageRange {
            get {
                return ResourceManager.GetString("Warn_PageRange", resourceCulture);
            }
        }
    }
}
