//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPDFKit.Controls.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Compare {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Compare() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComPDFKit.Controls.Strings.Compare", typeof(Compare).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorBurn.
        /// </summary>
        internal static string Blend_ColorBurn {
            get {
                return ResourceManager.GetString("Blend_ColorBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorDodge.
        /// </summary>
        internal static string Blend_ColorDodge {
            get {
                return ResourceManager.GetString("Blend_ColorDodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        internal static string Blend_Colour {
            get {
                return ResourceManager.GetString("Blend_Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darken.
        /// </summary>
        internal static string Blend_Darken {
            get {
                return ResourceManager.GetString("Blend_Darken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        internal static string Blend_Difference {
            get {
                return ResourceManager.GetString("Blend_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion.
        /// </summary>
        internal static string Blend_Exclusion {
            get {
                return ResourceManager.GetString("Blend_Exclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardLight.
        /// </summary>
        internal static string Blend_HardLight {
            get {
                return ResourceManager.GetString("Blend_HardLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        internal static string Blend_Hue {
            get {
                return ResourceManager.GetString("Blend_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighten.
        /// </summary>
        internal static string Blend_Lighten {
            get {
                return ResourceManager.GetString("Blend_Lighten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosity.
        /// </summary>
        internal static string Blend_Luminosity {
            get {
                return ResourceManager.GetString("Blend_Luminosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        internal static string Blend_Multiply {
            get {
                return ResourceManager.GetString("Blend_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Blend_Normal {
            get {
                return ResourceManager.GetString("Blend_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string Blend_Overlay {
            get {
                return ResourceManager.GetString("Blend_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string Blend_Saturation {
            get {
                return ResourceManager.GetString("Blend_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string Blend_Screen {
            get {
                return ResourceManager.GetString("Blend_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftLight.
        /// </summary>
        internal static string Blend_SoftLight {
            get {
                return ResourceManager.GetString("Blend_SoftLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Settings.
        /// </summary>
        internal static string Box_Comparison {
            get {
                return ResourceManager.GetString("Box_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Range.
        /// </summary>
        internal static string Box_PageRange {
            get {
                return ResourceManager.GetString("Box_PageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string Box_SaveAs {
            get {
                return ResourceManager.GetString("Box_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Button_Compare {
            get {
                return ResourceManager.GetString("Button_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfirm.
        /// </summary>
        internal static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Check_Image {
            get {
                return ResourceManager.GetString("Check_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Sync.
        /// </summary>
        internal static string Check_Sync {
            get {
                return ResourceManager.GetString("Check_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Check_Text {
            get {
                return ResourceManager.GetString("Check_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string Cmb_AddFile {
            get {
                return ResourceManager.GetString("Cmb_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Content.
        /// </summary>
        internal static string Content_Deleted {
            get {
                return ResourceManager.GetString("Content_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Content.
        /// </summary>
        internal static string Content_Insert {
            get {
                return ResourceManager.GetString("Content_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Content.
        /// </summary>
        internal static string Content_Replaced {
            get {
                return ResourceManager.GetString("Content_Replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Image.
        /// </summary>
        internal static string Delete_Image {
            get {
                return ResourceManager.GetString("Delete_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Page.
        /// </summary>
        internal static string Delete_Page {
            get {
                return ResourceManager.GetString("Delete_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Text.
        /// </summary>
        internal static string Delete_Text {
            get {
                return ResourceManager.GetString("Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page range that you selected is invalid. Please select again..
        /// </summary>
        internal static string Error_InvalidPage {
            get {
                return ResourceManager.GetString("Error_InvalidPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 2 files to compare.
        /// </summary>
        internal static string Error_SelectFile {
            get {
                return ResourceManager.GetString("Error_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 2 different documents to compare..
        /// </summary>
        internal static string Error_SelectSameFile {
            get {
                return ResourceManager.GetString("Error_SelectSameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Image.
        /// </summary>
        internal static string Insert_Image {
            get {
                return ResourceManager.GetString("Insert_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Page.
        /// </summary>
        internal static string Insert_Page {
            get {
                return ResourceManager.GetString("Insert_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Text.
        /// </summary>
        internal static string Insert_Text {
            get {
                return ResourceManager.GetString("Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Image.
        /// </summary>
        internal static string Replaced_Image {
            get {
                return ResourceManager.GetString("Replaced_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Text.
        /// </summary>
        internal static string Replaced_Text {
            get {
                return ResourceManager.GetString("Replaced_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge into a New File.
        /// </summary>
        internal static string Select_Merge {
            get {
                return ResourceManager.GetString("Select_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File .
        /// </summary>
        internal static string Select_NewFile {
            get {
                return ResourceManager.GetString("Select_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old File.
        /// </summary>
        internal static string Select_OldFile {
            get {
                return ResourceManager.GetString("Select_OldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend Mode.
        /// </summary>
        internal static string Setting_Blend {
            get {
                return ResourceManager.GetString("Setting_Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Items.
        /// </summary>
        internal static string Setting_Items {
            get {
                return ResourceManager.GetString("Setting_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Differences.
        /// </summary>
        internal static string Setting_MarkDifference {
            get {
                return ResourceManager.GetString("Setting_MarkDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Setting_Opacity {
            get {
                return ResourceManager.GetString("Setting_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Comparison.
        /// </summary>
        internal static string Tab_ContentComparison {
            get {
                return ResourceManager.GetString("Tab_ContentComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Comparison.
        /// </summary>
        internal static string Tab_OverlayComparison {
            get {
                return ResourceManager.GetString("Tab_OverlayComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Text_Page {
            get {
                return ResourceManager.GetString("Text_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Comparison Result Are Coming Soon.
        /// </summary>
        internal static string Tip_Progress {
            get {
                return ResourceManager.GetString("Tip_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Title_Attention {
            get {
                return ResourceManager.GetString("Title_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Documents.
        /// </summary>
        internal static string Title_CompareDoc {
            get {
                return ResourceManager.GetString("Title_CompareDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Title_Delete {
            get {
                return ResourceManager.GetString("Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differences List.
        /// </summary>
        internal static string Title_DifferenceList {
            get {
                return ResourceManager.GetString("Title_DifferenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Differences.
        /// </summary>
        internal static string Title_DifferenceNum {
            get {
                return ResourceManager.GetString("Title_DifferenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no difference between 2 documents..
        /// </summary>
        internal static string Title_EmptyResult {
            get {
                return ResourceManager.GetString("Title_EmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        internal static string Title_FileLocation {
            get {
                return ResourceManager.GetString("Title_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted.
        /// </summary>
        internal static string Title_Insert {
            get {
                return ResourceManager.GetString("Title_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page Range.
        /// </summary>
        internal static string Title_InvalidPage {
            get {
                return ResourceManager.GetString("Title_InvalidPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        internal static string Title_NewFile {
            get {
                return ResourceManager.GetString("Title_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old File.
        /// </summary>
        internal static string Title_OldFile {
            get {
                return ResourceManager.GetString("Title_OldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced.
        /// </summary>
        internal static string Title_Replace {
            get {
                return ResourceManager.GetString("Title_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string Title_SelectFile {
            get {
                return ResourceManager.GetString("Title_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string Title_Thumbnail {
            get {
                return ResourceManager.GetString("Title_Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Add.
        /// </summary>
        internal static string Tooltip_AddFile {
            get {
                return ResourceManager.GetString("Tooltip_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Differences List.
        /// </summary>
        internal static string Tooltip_CloseList {
            get {
                return ResourceManager.GetString("Tooltip_CloseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Differences List.
        /// </summary>
        internal static string Tooltip_OpenList {
            get {
                return ResourceManager.GetString("Tooltip_OpenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you have saved the comparison results file!.
        /// </summary>
        internal static string Warn_Save {
            get {
                return ResourceManager.GetString("Warn_Save", resourceCulture);
            }
        }
    }
}
