//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPDFKit.Controls.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Compress {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Compress() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComPDFKit.Controls.Strings.Compress", typeof(Compress).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Compress_Custom {
            get {
                return ResourceManager.GetString("Compress_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string Compress_High {
            get {
                return ResourceManager.GetString("Compress_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Compress_Low {
            get {
                return ResourceManager.GetString("Compress_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Compress_Medium {
            get {
                return ResourceManager.GetString("Compress_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size entered is incorrect, try again please.
        /// </summary>
        internal static string Compress_NumberErrorWarning {
            get {
                return ResourceManager.GetString("Compress_NumberErrorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress files succeeded!.
        /// </summary>
        internal static string Compress_OKWarning {
            get {
                return ResourceManager.GetString("Compress_OKWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress Quality.
        /// </summary>
        internal static string Compress_OptimizationQuality {
            get {
                return ResourceManager.GetString("Compress_OptimizationQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to stop the compressing?.
        /// </summary>
        internal static string CompressInterruptWarning {
            get {
                return ResourceManager.GetString("CompressInterruptWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string CompressStr {
            get {
                return ResourceManager.GetString("CompressStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string ContentSelection_CancelDo {
            get {
                return ResourceManager.GetString("ContentSelection_CancelDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ContentSelection_Exit {
            get {
                return ResourceManager.GetString("ContentSelection_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string ContentSelection_Output {
            get {
                return ResourceManager.GetString("ContentSelection_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Convert_Progress {
            get {
                return ResourceManager.GetString("Convert_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Area.
        /// </summary>
        internal static string Corp_Customize {
            get {
                return ResourceManager.GetString("Corp_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page cannot be restored to original state after you have cropped it. Are you sure you want to crop the page?.
        /// </summary>
        internal static string Corp_Customize_PRM {
            get {
                return ResourceManager.GetString("Corp_Customize_PRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string FileInfo_Location {
            get {
                return ResourceManager.GetString("FileInfo_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FileInfo_Size {
            get {
                return ResourceManager.GetString("FileInfo_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        internal static string Main_AddFile {
            get {
                return ResourceManager.GetString("Main_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Main_Cancel {
            get {
                return ResourceManager.GetString("Main_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Main_CompletedState {
            get {
                return ResourceManager.GetString("Main_CompletedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Main_Copy {
            get {
                return ResourceManager.GetString("Main_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string Main_Crop {
            get {
                return ResourceManager.GetString("Main_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Main_Delete {
            get {
                return ResourceManager.GetString("Main_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Main_FailedState {
            get {
                return ResourceManager.GetString("Main_FailedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string Main_FileName {
            get {
                return ResourceManager.GetString("Main_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Main_HintWarningTitle {
            get {
                return ResourceManager.GetString("Main_HintWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt.
        /// </summary>
        internal static string Main_Interrupt {
            get {
                return ResourceManager.GetString("Main_Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string Main_MenuHelp_About {
            get {
                return ResourceManager.GetString("Main_MenuHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Main_No {
            get {
                return ResourceManager.GetString("Main_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string Main_NoSelectedFilesWarning {
            get {
                return ResourceManager.GetString("Main_NoSelectedFilesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Main_Ok {
            get {
                return ResourceManager.GetString("Main_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cannot be opened because the file format or file extension is invalid. Please make sure the file is not damaged and the file extension matches the file format..
        /// </summary>
        internal static string Main_OpenFileFailedWarning {
            get {
                return ResourceManager.GetString("Main_OpenFileFailedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder.
        /// </summary>
        internal static string Main_OpenFolderNoteWarning {
            get {
                return ResourceManager.GetString("Main_OpenFolderNoteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Main_Print {
            get {
                return ResourceManager.GetString("Main_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Files.
        /// </summary>
        internal static string Main_RemoveAll {
            get {
                return ResourceManager.GetString("Main_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Main_Yes {
            get {
                return ResourceManager.GetString("Main_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string Merge_MoveDown {
            get {
                return ResourceManager.GetString("Merge_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string Merge_MoveUp {
            get {
                return ResourceManager.GetString("Merge_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) in total.
        /// </summary>
        internal static string Merge_TotalPage {
            get {
                return ResourceManager.GetString("Merge_TotalPage", resourceCulture);
            }
        }
    }
}
