//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPDFKit.Controls.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComPDFKit.Controls.Strings.PropertyPanel", typeof(PropertyPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Pages.
        /// </summary>
        internal static string Action_Jump {
            get {
                return ResourceManager.GetString("Action_Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Web Link.
        /// </summary>
        internal static string Action_Link {
            get {
                return ResourceManager.GetString("Action_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Action_None {
            get {
                return ResourceManager.GetString("Action_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Alignment_Center {
            get {
                return ResourceManager.GetString("Alignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Alignment_Left {
            get {
                return ResourceManager.GetString("Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Alignment_Right {
            get {
                return ResourceManager.GetString("Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Board_Angle {
            get {
                return ResourceManager.GetString("Board_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Board_Area {
            get {
                return ResourceManager.GetString("Board_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Board_Length {
            get {
                return ResourceManager.GetString("Board_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        internal static string Board_Precision {
            get {
                return ResourceManager.GetString("Board_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Board_Scale {
            get {
                return ResourceManager.GetString("Board_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Board_Settings {
            get {
                return ResourceManager.GetString("Board_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Board_X {
            get {
                return ResourceManager.GetString("Board_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Board_Y {
            get {
                return ResourceManager.GetString("Board_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        internal static string Btn_Action {
            get {
                return ResourceManager.GetString("Btn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        internal static string Btn_SelectAtction {
            get {
                return ResourceManager.GetString("Btn_SelectAtction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Button_Done {
            get {
                return ResourceManager.GetString("Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Button_Image {
            get {
                return ResourceManager.GetString("Button_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Button_Keyboard {
            get {
                return ResourceManager.GetString("Button_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Button_Left {
            get {
                return ResourceManager.GetString("Button_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Signature.
        /// </summary>
        internal static string Button_NewSig {
            get {
                return ResourceManager.GetString("Button_NewSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Button_Right {
            get {
                return ResourceManager.GetString("Button_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad.
        /// </summary>
        internal static string Button_Trackpad {
            get {
                return ResourceManager.GetString("Button_Trackpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (YYYY-MM-dd).
        /// </summary>
        internal static string Check_Date {
            get {
                return ResourceManager.GetString("Check_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Style.
        /// </summary>
        internal static string Check_Style {
            get {
                return ResourceManager.GetString("Check_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (HH:mm:ss).
        /// </summary>
        internal static string Check_Time {
            get {
                return ResourceManager.GetString("Check_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Stamp.
        /// </summary>
        internal static string Custom_Image {
            get {
                return ResourceManager.GetString("Custom_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Stamp.
        /// </summary>
        internal static string Custom_Text {
            get {
                return ResourceManager.GetString("Custom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Font_Bold {
            get {
                return ResourceManager.GetString("Font_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Oblique.
        /// </summary>
        internal static string Font_BoldOblique {
            get {
                return ResourceManager.GetString("Font_BoldOblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Font_Light {
            get {
                return ResourceManager.GetString("Font_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Oblique.
        /// </summary>
        internal static string Font_LightOblique {
            get {
                return ResourceManager.GetString("Font_LightOblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblique.
        /// </summary>
        internal static string Font_Oblique {
            get {
                return ResourceManager.GetString("Font_Oblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string Font_Regular {
            get {
                return ResourceManager.GetString("Font_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button 1.
        /// </summary>
        internal static string Holder_Btn {
            get {
                return ResourceManager.GetString("Holder_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Button.
        /// </summary>
        internal static string Holder_BtnContent {
            get {
                return ResourceManager.GetString("Holder_BtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box_2023-05-30 11:32:26.
        /// </summary>
        internal static string Holder_Chb {
            get {
                return ResourceManager.GetString("Holder_Chb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Button_1.
        /// </summary>
        internal static string Holder_Cmb {
            get {
                return ResourceManager.GetString("Holder_Cmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@compdf.com.
        /// </summary>
        internal static string Holder_Email {
            get {
                return ResourceManager.GetString("Holder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Page Number Between 1 ~.
        /// </summary>
        internal static string Holder_Jump {
            get {
                return ResourceManager.GetString("Holder_Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Box 1.
        /// </summary>
        internal static string Holder_ListBox {
            get {
                return ResourceManager.GetString("Holder_ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 1.
        /// </summary>
        internal static string Holder_Rdo {
            get {
                return ResourceManager.GetString("Holder_Rdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 180° to 180°.
        /// </summary>
        internal static string Holder_Rotation {
            get {
                return ResourceManager.GetString("Holder_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Field 1.
        /// </summary>
        internal static string Holder_TextField {
            get {
                return ResourceManager.GetString("Holder_TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.compdf.com/.
        /// </summary>
        internal static string Holder_URL {
            get {
                return ResourceManager.GetString("Holder_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number.
        /// </summary>
        internal static string Jump_Page {
            get {
                return ResourceManager.GetString("Jump_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arrow (blue).
        /// </summary>
        internal static string Left_Blue {
            get {
                return ResourceManager.GetString("Left_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arrow (green).
        /// </summary>
        internal static string Left_Green {
            get {
                return ResourceManager.GetString("Left_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arrow (red).
        /// </summary>
        internal static string Left_Red {
            get {
                return ResourceManager.GetString("Left_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File.
        /// </summary>
        internal static string Link_SelectFile {
            get {
                return ResourceManager.GetString("Link_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LinkType_Email {
            get {
                return ResourceManager.GetString("LinkType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Pages.
        /// </summary>
        internal static string LinkType_Jump {
            get {
                return ResourceManager.GetString("LinkType_Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string LinkType_URL {
            get {
                return ResourceManager.GetString("LinkType_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Option_Hidden {
            get {
                return ResourceManager.GetString("Option_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Select.
        /// </summary>
        internal static string Option_MultiSelect {
            get {
                return ResourceManager.GetString("Option_MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible but doesn&apos;t print.
        /// </summary>
        internal static string Option_NoPrint {
            get {
                return ResourceManager.GetString("Option_NoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden but printable.
        /// </summary>
        internal static string Option_Print {
            get {
                return ResourceManager.GetString("Option_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Border.
        /// </summary>
        internal static string Option_ShowBorder {
            get {
                return ResourceManager.GetString("Option_ShowBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Option_Visible {
            get {
                return ResourceManager.GetString("Option_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Preview_Image {
            get {
                return ResourceManager.GetString("Preview_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Preview_Text {
            get {
                return ResourceManager.GetString("Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Property_Alignment {
            get {
                return ResourceManager.GetString("Property_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string Property_BgColor {
            get {
                return ResourceManager.GetString("Property_BgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Property_Color {
            get {
                return ResourceManager.GetString("Property_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string Property_DefaultValue {
            get {
                return ResourceManager.GetString("Property_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Property_End {
            get {
                return ResourceManager.GetString("Property_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Color.
        /// </summary>
        internal static string Property_FillColor {
            get {
                return ResourceManager.GetString("Property_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        internal static string Property_Flip {
            get {
                return ResourceManager.GetString("Property_Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Property_Font {
            get {
                return ResourceManager.GetString("Property_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string Property_FontColor {
            get {
                return ResourceManager.GetString("Property_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string Property_FontSize {
            get {
                return ResourceManager.GetString("Property_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Style.
        /// </summary>
        internal static string Property_FontStyle {
            get {
                return ResourceManager.GetString("Property_FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Color.
        /// </summary>
        internal static string Property_LineColor {
            get {
                return ResourceManager.GetString("Property_LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line and Border Shape.
        /// </summary>
        internal static string Property_LineShape {
            get {
                return ResourceManager.GetString("Property_LineShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line and Border Style.
        /// </summary>
        internal static string Property_LineStyle {
            get {
                return ResourceManager.GetString("Property_LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Width.
        /// </summary>
        internal static string Property_LineWidth {
            get {
                return ResourceManager.GetString("Property_LineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-line.
        /// </summary>
        internal static string Property_MultiLine {
            get {
                return ResourceManager.GetString("Property_MultiLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Property_Name {
            get {
                return ResourceManager.GetString("Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Property_Note {
            get {
                return ResourceManager.GetString("Property_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Property_Opacity {
            get {
                return ResourceManager.GetString("Property_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Opacity.
        /// </summary>
        internal static string Property_Opacity_M {
            get {
                return ResourceManager.GetString("Property_Opacity_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Property_Rotate {
            get {
                return ResourceManager.GetString("Property_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Angle.
        /// </summary>
        internal static string Property_Rotation {
            get {
                return ResourceManager.GetString("Property_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Property_Start {
            get {
                return ResourceManager.GetString("Property_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke Color.
        /// </summary>
        internal static string Property_StrokeColor {
            get {
                return ResourceManager.GetString("Property_StrokeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Property_Tool {
            get {
                return ResourceManager.GetString("Property_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Field.
        /// </summary>
        internal static string Property_Visibility {
            get {
                return ResourceManager.GetString("Property_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle (blue).
        /// </summary>
        internal static string Rec_Blue {
            get {
                return ResourceManager.GetString("Rec_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle (green).
        /// </summary>
        internal static string Rec_Green {
            get {
                return ResourceManager.GetString("Rec_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle (red).
        /// </summary>
        internal static string Rec_Red {
            get {
                return ResourceManager.GetString("Rec_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow (blue).
        /// </summary>
        internal static string Right_Blue {
            get {
                return ResourceManager.GetString("Right_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow (green).
        /// </summary>
        internal static string Right_Green {
            get {
                return ResourceManager.GetString("Right_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow (red).
        /// </summary>
        internal static string Right_Red {
            get {
                return ResourceManager.GetString("Right_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string Scale_CM {
            get {
                return ResourceManager.GetString("Scale_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string Scale_FT {
            get {
                return ResourceManager.GetString("Scale_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string Scale_IN {
            get {
                return ResourceManager.GetString("Scale_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string Scale_KM {
            get {
                return ResourceManager.GetString("Scale_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Scale_M {
            get {
                return ResourceManager.GetString("Scale_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string Scale_MI {
            get {
                return ResourceManager.GetString("Scale_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string Scale_MM {
            get {
                return ResourceManager.GetString("Scale_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        internal static string Scale_PT {
            get {
                return ResourceManager.GetString("Scale_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        internal static string Scale_YD {
            get {
                return ResourceManager.GetString("Scale_YD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Setting_Font {
            get {
                return ResourceManager.GetString("Setting_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Stamp_Color {
            get {
                return ResourceManager.GetString("Stamp_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Stamp_Custom {
            get {
                return ResourceManager.GetString("Stamp_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Stamp_Standard {
            get {
                return ResourceManager.GetString("Stamp_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Stamp_Style {
            get {
                return ResourceManager.GetString("Stamp_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp Template.
        /// </summary>
        internal static string Stamp_Template {
            get {
                return ResourceManager.GetString("Stamp_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Stamp_Text {
            get {
                return ResourceManager.GetString("Stamp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Style_Check {
            get {
                return ResourceManager.GetString("Style_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Style_Circle {
            get {
                return ResourceManager.GetString("Style_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross.
        /// </summary>
        internal static string Style_Cross {
            get {
                return ResourceManager.GetString("Style_Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button is checked by default.
        /// </summary>
        internal static string Style_Default {
            get {
                return ResourceManager.GetString("Style_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        internal static string Style_Diamond {
            get {
                return ResourceManager.GetString("Style_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Style.
        /// </summary>
        internal static string Style_General {
            get {
                return ResourceManager.GetString("Style_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Style_Square {
            get {
                return ResourceManager.GetString("Style_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string Style_Star {
            get {
                return ResourceManager.GetString("Style_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing dimensions: Actual size.
        /// </summary>
        internal static string Text_Dimensions {
            get {
                return ResourceManager.GetString("Text_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Image here or.
        /// </summary>
        internal static string Text_DropImage {
            get {
                return ResourceManager.GetString("Text_DropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property panel is empty.
        /// </summary>
        internal static string Text_EmptyPanel {
            get {
                return ResourceManager.GetString("Text_EmptyPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item in the item list to make it the default option..
        /// </summary>
        internal static string Tip_Default {
            get {
                return ResourceManager.GetString("Tip_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete？.
        /// </summary>
        internal static string Tip_Delete {
            get {
                return ResourceManager.GetString("Tip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a set of mutually exclusive radio buttons (i.e., where only one can be selected at a time), please give the fields the same name to let buttons in one group..
        /// </summary>
        internal static string Tip_SingleRdo {
            get {
                return ResourceManager.GetString("Tip_SingleRdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Title_Appearance {
            get {
                return ResourceManager.GetString("Title_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Title_Appearance_M {
            get {
                return ResourceManager.GetString("Title_Appearance_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        internal static string Title_Arrow {
            get {
                return ResourceManager.GetString("Title_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Button.
        /// </summary>
        internal static string Title_Btn {
            get {
                return ResourceManager.GetString("Title_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Title_BtnContent {
            get {
                return ResourceManager.GetString("Title_BtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Caption.
        /// </summary>
        internal static string Title_Caption {
            get {
                return ResourceManager.GetString("Title_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box.
        /// </summary>
        internal static string Title_Chb {
            get {
                return ResourceManager.GetString("Title_Chb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Title_Circle {
            get {
                return ResourceManager.GetString("Title_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        internal static string Title_Cloud {
            get {
                return ResourceManager.GetString("Title_Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Button.
        /// </summary>
        internal static string Title_Cmb {
            get {
                return ResourceManager.GetString("Title_Cmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeText.
        /// </summary>
        internal static string Title_FreeText {
            get {
                return ResourceManager.GetString("Title_FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Title_General {
            get {
                return ResourceManager.GetString("Title_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Title_Highlight {
            get {
                return ResourceManager.GetString("Title_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Properties.
        /// </summary>
        internal static string Title_ImageProperty {
            get {
                return ResourceManager.GetString("Title_ImageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink.
        /// </summary>
        internal static string Title_Ink {
            get {
                return ResourceManager.GetString("Title_Ink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Title_Item {
            get {
                return ResourceManager.GetString("Title_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        internal static string Title_ItemList {
            get {
                return ResourceManager.GetString("Title_ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Title_Line {
            get {
                return ResourceManager.GetString("Title_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Box.
        /// </summary>
        internal static string Title_ListBox {
            get {
                return ResourceManager.GetString("Title_ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Title_Note {
            get {
                return ResourceManager.GetString("Title_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Properties.
        /// </summary>
        internal static string Title_PathProperty {
            get {
                return ResourceManager.GetString("Title_PathProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Title_Preferences {
            get {
                return ResourceManager.GetString("Title_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Title_Preview {
            get {
                return ResourceManager.GetString("Title_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Button.
        /// </summary>
        internal static string Title_Rdo {
            get {
                return ResourceManager.GetString("Title_Rdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Title_Scale {
            get {
                return ResourceManager.GetString("Title_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures.
        /// </summary>
        internal static string Title_Sig {
            get {
                return ResourceManager.GetString("Title_Sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Title_Square {
            get {
                return ResourceManager.GetString("Title_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squiggly.
        /// </summary>
        internal static string Title_Squiggly {
            get {
                return ResourceManager.GetString("Title_Squiggly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        internal static string Title_Stamp {
            get {
                return ResourceManager.GetString("Title_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikeout.
        /// </summary>
        internal static string Title_Strikeout {
            get {
                return ResourceManager.GetString("Title_Strikeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Field.
        /// </summary>
        internal static string Title_TextField {
            get {
                return ResourceManager.GetString("Title_TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Properties.
        /// </summary>
        internal static string Title_TextProperty {
            get {
                return ResourceManager.GetString("Title_TextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Title_Underline {
            get {
                return ResourceManager.GetString("Title_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 button is in the group. At least 2 buttons are needed in a group..
        /// </summary>
        internal static string Warn_SingleRdo {
            get {
                return ResourceManager.GetString("Warn_SingleRdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale is not greater than zero..
        /// </summary>
        internal static string Warn_WrongScale {
            get {
                return ResourceManager.GetString("Warn_WrongScale", resourceCulture);
            }
        }
    }
}
