//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPDFKit.Controls.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Security {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Security() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComPDFKit.Controls.Strings.Security", typeof(Security).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        internal static string Button_AddFiles {
            get {
                return ResourceManager.GetString("Button_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string Button_Decrypt {
            get {
                return ResourceManager.GetString("Button_Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string Button_Encrypt {
            get {
                return ResourceManager.GetString("Button_Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and Select your watermark image..
        /// </summary>
        internal static string Button_ImageWatermark {
            get {
                return ResourceManager.GetString("Button_ImageWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Files.
        /// </summary>
        internal static string Button_RemoveAll {
            get {
                return ResourceManager.GetString("Button_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Files.
        /// </summary>
        internal static string Button_RemoveSelected {
            get {
                return ResourceManager.GetString("Button_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict content copying.
        /// </summary>
        internal static string Chk_NoCopy {
            get {
                return ResourceManager.GetString("Chk_NoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict document printing.
        /// </summary>
        internal static string Chk_NoPrint {
            get {
                return ResourceManager.GetString("Chk_NoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the password to open the document.
        /// </summary>
        internal static string Chk_OpenPassword {
            get {
                return ResourceManager.GetString("Chk_OpenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the owner password for this document.
        /// </summary>
        internal static string Chk_OwnerPassword {
            get {
                return ResourceManager.GetString("Chk_OwnerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        internal static string Chk_Tile {
            get {
                return ResourceManager.GetString("Chk_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark_Removed.
        /// </summary>
        internal static string FileName_RemoveWatermark {
            get {
                return ResourceManager.GetString("FileName_RemoveWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        internal static string FileName_Watermark {
            get {
                return ResourceManager.GetString("FileName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string Holder_EnterPassword {
            get {
                return ResourceManager.GetString("Holder_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the owner`s password.
        /// </summary>
        internal static string Holder_OwnerPassword {
            get {
                return ResourceManager.GetString("Holder_OwnerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your watermark text here..
        /// </summary>
        internal static string Holder_TextWatermark {
            get {
                return ResourceManager.GetString("Holder_TextWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128-bit AES.
        /// </summary>
        internal static string Option_128AES {
            get {
                return ResourceManager.GetString("Option_128AES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128-bit RC4.
        /// </summary>
        internal static string Option_128RC4 {
            get {
                return ResourceManager.GetString("Option_128RC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256-bit AES.
        /// </summary>
        internal static string Option_256AES {
            get {
                return ResourceManager.GetString("Option_256AES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pages.
        /// </summary>
        internal static string Option_AllPages {
            get {
                return ResourceManager.GetString("Option_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Passwords.
        /// </summary>
        internal static string Rdo_AddPassword {
            get {
                return ResourceManager.GetString("Rdo_AddPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Watermarks.
        /// </summary>
        internal static string Rdo_AddWatermarks {
            get {
                return ResourceManager.GetString("Rdo_AddWatermarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages in range.
        /// </summary>
        internal static string Rdo_AllPages {
            get {
                return ResourceManager.GetString("Rdo_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behind the text.
        /// </summary>
        internal static string Rdo_Behind {
            get {
                return ResourceManager.GetString("Rdo_Behind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom pages .
        /// </summary>
        internal static string Rdo_CustomPages {
            get {
                return ResourceManager.GetString("Rdo_CustomPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even pages only.
        /// </summary>
        internal static string Rdo_EvenPages {
            get {
                return ResourceManager.GetString("Rdo_EvenPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In front of the text.
        /// </summary>
        internal static string Rdo_Front {
            get {
                return ResourceManager.GetString("Rdo_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Watermark.
        /// </summary>
        internal static string Rdo_ImageWatermark {
            get {
                return ResourceManager.GetString("Rdo_ImageWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd pages only .
        /// </summary>
        internal static string Rdo_OddPages {
            get {
                return ResourceManager.GetString("Rdo_OddPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Passwords.
        /// </summary>
        internal static string Rdo_RemovePassword {
            get {
                return ResourceManager.GetString("Rdo_RemovePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Watermarks.
        /// </summary>
        internal static string Rdo_RemoveWatermark {
            get {
                return ResourceManager.GetString("Rdo_RemoveWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Watermark.
        /// </summary>
        internal static string Rdo_TextWatermark {
            get {
                return ResourceManager.GetString("Rdo_TextWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string Table_FileName {
            get {
                return ResourceManager.GetString("Table_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Table_FileSize {
            get {
                return ResourceManager.GetString("Table_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Range.
        /// </summary>
        internal static string Table_PageRange {
            get {
                return ResourceManager.GetString("Table_PageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Table_Path {
            get {
                return ResourceManager.GetString("Table_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string Text_Algorithm {
            get {
                return ResourceManager.GetString("Text_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page.
        /// </summary>
        internal static string Text_CurrentPage {
            get {
                return ResourceManager.GetString("Text_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Settings.
        /// </summary>
        internal static string Text_EmptyPassword {
            get {
                return ResourceManager.GetString("Text_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected.
        /// </summary>
        internal static string Text_EmptyPath {
            get {
                return ResourceManager.GetString("Text_EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Level.
        /// </summary>
        internal static string Text_EncryptionLevel {
            get {
                return ResourceManager.GetString("Text_EncryptionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) in Total: .
        /// </summary>
        internal static string Text_FileCount {
            get {
                return ResourceManager.GetString("Text_FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string Text_FontColor {
            get {
                return ResourceManager.GetString("Text_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Options.
        /// </summary>
        internal static string Text_Layout {
            get {
                return ResourceManager.GetString("Text_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Text_Opacity {
            get {
                return ResourceManager.GetString("Text_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Types.
        /// </summary>
        internal static string Text_OperationType {
            get {
                return ResourceManager.GetString("Text_OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Range.
        /// </summary>
        internal static string Text_PageRange {
            get {
                return ResourceManager.GetString("Text_PageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Text_Permisions {
            get {
                return ResourceManager.GetString("Text_Permisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Text_Preview {
            get {
                return ResourceManager.GetString("Text_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string Text_Ratio {
            get {
                return ResourceManager.GetString("Text_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string Text_Rotation {
            get {
                return ResourceManager.GetString("Text_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        internal static string Text_SecuritySettings {
            get {
                return ResourceManager.GetString("Text_SecuritySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support: Numbers, letters, @, $, !, %, ?, &amp;.
        /// </summary>
        internal static string Text_Support {
            get {
                return ResourceManager.GetString("Text_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Password Remover is an easy-to-use PDF security remover,which helps users decrypt PDF protections and remove restrictions on printing,editing and copying..
        /// </summary>
        internal static string Tip_EasyUse {
            get {
                return ResourceManager.GetString("Tip_EasyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If open password is required,you need to enter the right password first and then remove protections from PDF files..
        /// </summary>
        internal static string Tip_Require {
            get {
                return ResourceManager.GetString("Tip_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Watermarks.
        /// </summary>
        internal static string Title_AddWatermark {
            get {
                return ResourceManager.GetString("Title_AddWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Document.
        /// </summary>
        internal static string Title_OpenPassword {
            get {
                return ResourceManager.GetString("Title_OpenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Type.
        /// </summary>
        internal static string Title_OperationType {
            get {
                return ResourceManager.GetString("Title_OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Settings.
        /// </summary>
        internal static string Title_OwnerPassword {
            get {
                return ResourceManager.GetString("Title_OwnerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Title_Password {
            get {
                return ResourceManager.GetString("Title_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Security.
        /// </summary>
        internal static string Title_RemoveSecurity {
            get {
                return ResourceManager.GetString("Title_RemoveSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Watermarks.
        /// </summary>
        internal static string Title_RemoveWatermark {
            get {
                return ResourceManager.GetString("Title_RemoveWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        internal static string Title_Security {
            get {
                return ResourceManager.GetString("Title_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        internal static string Title_Watermark {
            get {
                return ResourceManager.GetString("Title_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Settings.
        /// </summary>
        internal static string Title_WatermarkSettings {
            get {
                return ResourceManager.GetString("Title_WatermarkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ToolTip_Next {
            get {
                return ResourceManager.GetString("ToolTip_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ToolTip_Previous {
            get {
                return ResourceManager.GetString("ToolTip_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can`t be empty..
        /// </summary>
        internal static string Warn_Empty {
            get {
                return ResourceManager.GetString("Warn_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can`t be empty..
        /// </summary>
        internal static string Warn_EmptyPassword {
            get {
                return ResourceManager.GetString("Warn_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected..
        /// </summary>
        internal static string Warn_EmptyWatermarkImage {
            get {
                return ResourceManager.GetString("Warn_EmptyWatermarkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Text input..
        /// </summary>
        internal static string Warn_EmptyWatermarkText {
            get {
                return ResourceManager.GetString("Warn_EmptyWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string Warn_InvaildPassword {
            get {
                return ResourceManager.GetString("Warn_InvaildPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password to open the document should be different from the owner`s password..
        /// </summary>
        internal static string Warn_SamePassword {
            get {
                return ResourceManager.GetString("Warn_SamePassword", resourceCulture);
            }
        }
    }
}
