//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComPDFKit.Controls.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Signature {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Signature() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComPDFKit.Controls.Strings.Signature", typeof(Signature).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Trusted Certificates.
        /// </summary>
        internal static string Button_AddTrust {
            get {
                return ResourceManager.GetString("Button_AddTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Signatures.
        /// </summary>
        internal static string Button_AllSig {
            get {
                return ResourceManager.GetString("Button_AllSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Details.
        /// </summary>
        internal static string Button_CertDetails {
            get {
                return ResourceManager.GetString("Button_CertDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature Details.
        /// </summary>
        internal static string Button_Details {
            get {
                return ResourceManager.GetString("Button_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Button_Finish {
            get {
                return ResourceManager.GetString("Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Details.
        /// </summary>
        internal static string Button_SigDetails {
            get {
                return ResourceManager.GetString("Button_SigDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Chk_Date {
            get {
                return ResourceManager.GetString("Chk_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguishable name.
        /// </summary>
        internal static string Chk_DN {
            get {
                return ResourceManager.GetString("Chk_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time Display Signature Validity.
        /// </summary>
        internal static string Chk_DynamicAP {
            get {
                return ResourceManager.GetString("Chk_DynamicAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Chk_Logo {
            get {
                return ResourceManager.GetString("Chk_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Chk_Name {
            get {
                return ResourceManager.GetString("Chk_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Chk_Position {
            get {
                return ResourceManager.GetString("Chk_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Chk_Reason {
            get {
                return ResourceManager.GetString("Chk_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComPDFKit Version.
        /// </summary>
        internal static string Chk_Version {
            get {
                return ResourceManager.GetString("Chk_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: .
        /// </summary>
        internal static string Cmb_Reason {
            get {
                return ResourceManager.GetString("Cmb_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your self-signed Digital ID.
        /// </summary>
        internal static string Describe_Create {
            get {
                return ResourceManager.GetString("Describe_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import an existing Digital ID that you have obtained as file.
        /// </summary>
        internal static string Describe_Import {
            get {
                return ResourceManager.GetString("Describe_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password again.
        /// </summary>
        internal static string Holder_ConfirmPassword {
            get {
                return ResourceManager.GetString("Holder_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        internal static string Holder_Email {
            get {
                return ResourceManager.GetString("Holder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        internal static string Holder_Name {
            get {
                return ResourceManager.GetString("Holder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the organization.
        /// </summary>
        internal static string Holder_Organization {
            get {
                return ResourceManager.GetString("Holder_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password of the certificate file.
        /// </summary>
        internal static string Holder_Password {
            get {
                return ResourceManager.GetString("Holder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate File.
        /// </summary>
        internal static string Holder_Path {
            get {
                return ResourceManager.GetString("Holder_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File.
        /// </summary>
        internal static string Holder_SelectFile {
            get {
                return ResourceManager.GetString("Holder_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string Holder_SetPassword {
            get {
                return ResourceManager.GetString("Holder_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the organization unit.
        /// </summary>
        internal static string Holder_Unit {
            get {
                return ResourceManager.GetString("Holder_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string InvalidPasswordError {
            get {
                return ResourceManager.GetString("InvalidPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am approving the document.
        /// </summary>
        internal static string Option_Approving {
            get {
                return ResourceManager.GetString("Option_Approving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Encryption.
        /// </summary>
        internal static string Option_Encrypt {
            get {
                return ResourceManager.GetString("Option_Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use A Digital ID from A File.
        /// </summary>
        internal static string Option_FileID {
            get {
                return ResourceManager.GetString("Option_FileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Option_Image {
            get {
                return ResourceManager.GetString("Option_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Option_Keyboard {
            get {
                return ResourceManager.GetString("Option_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A New Digital ID.
        /// </summary>
        internal static string Option_NewID {
            get {
                return ResourceManager.GetString("Option_NewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Option_None {
            get {
                return ResourceManager.GetString("Option_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am the owner of the document.
        /// </summary>
        internal static string Option_Owner {
            get {
                return ResourceManager.GetString("Option_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have reviewed this document.
        /// </summary>
        internal static string Option_Review {
            get {
                return ResourceManager.GetString("Option_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signatures.
        /// </summary>
        internal static string Option_Sign {
            get {
                return ResourceManager.GetString("Option_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signatures and Data Encryption.
        /// </summary>
        internal static string Option_SignAndEncrypt {
            get {
                return ResourceManager.GetString("Option_SignAndEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad.
        /// </summary>
        internal static string Option_Trackpad {
            get {
                return ResourceManager.GetString("Option_Trackpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am approving the document.
        /// </summary>
        internal static string Reason_Approving {
            get {
                return ResourceManager.GetString("Reason_Approving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; None &gt;.
        /// </summary>
        internal static string Reason_None {
            get {
                return ResourceManager.GetString("Reason_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am the owner of the document.
        /// </summary>
        internal static string Reason_Owner {
            get {
                return ResourceManager.GetString("Reason_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have reviewed this document.
        /// </summary>
        internal static string Reason_Reviewed {
            get {
                return ResourceManager.GetString("Reason_Reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm: .
        /// </summary>
        internal static string Text_Algorithm {
            get {
                return ResourceManager.GetString("Text_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Constraints:.
        /// </summary>
        internal static string Text_BasicConstraints {
            get {
                return ResourceManager.GetString("Text_BasicConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Policy:.
        /// </summary>
        internal static string Text_CertPolicy {
            get {
                return ResourceManager.GetString("Text_CertPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Viewer.
        /// </summary>
        internal static string Text_CertViewer {
            get {
                return ResourceManager.GetString("Text_CertViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRL Distribution Points:.
        /// </summary>
        internal static string Text_CRL {
            get {
                return ResourceManager.GetString("Text_CRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string Text_Date {
            get {
                return ResourceManager.GetString("Text_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete it?.
        /// </summary>
        internal static string Text_Delete_ {
            get {
                return ResourceManager.GetString("Text_Delete ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Text_Details {
            get {
                return ResourceManager.GetString("Text_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was signed with a certificate that has expired. If you acquired this file recently, it may not be authentic..
        /// </summary>
        internal static string Text_Expired {
            get {
                return ResourceManager.GetString("Text_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signer&apos;s identity is invalid..
        /// </summary>
        internal static string Text_IDInvalid_ {
            get {
                return ResourceManager.GetString("Text_IDInvalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signer&apos;s identity is valid..
        /// </summary>
        internal static string Text_IDValid_ {
            get {
                return ResourceManager.GetString("Text_IDValid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Signature, .
        /// </summary>
        internal static string Text_Invalid {
            get {
                return ResourceManager.GetString("Text_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued to: .
        /// </summary>
        internal static string Text_IssuedTo {
            get {
                return ResourceManager.GetString("Text_IssuedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer: .
        /// </summary>
        internal static string Text_Issuer {
            get {
                return ResourceManager.GetString("Text_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer‘s Key Identifier: .
        /// </summary>
        internal static string Text_IssuerID {
            get {
                return ResourceManager.GetString("Text_IssuerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Information Access: .
        /// </summary>
        internal static string Text_IssuerInfo {
            get {
                return ResourceManager.GetString("Text_IssuerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Usage: .
        /// </summary>
        internal static string Text_KeyUsage {
            get {
                return ResourceManager.GetString("Text_KeyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 Digest: .
        /// </summary>
        internal static string Text_MD5 {
            get {
                return ResourceManager.GetString("Text_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been altered or corrupted since it was signed by the current user..
        /// </summary>
        internal static string Text_Modified_ {
            get {
                return ResourceManager.GetString("Text_Modified ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one signature is invalid..
        /// </summary>
        internal static string Text_MultiSig {
            get {
                return ResourceManager.GetString("Text_MultiSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has not been modified since this signature was applied..
        /// </summary>
        internal static string Text_NotModified_ {
            get {
                return ResourceManager.GetString("Text_NotModified ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key: .
        /// </summary>
        internal static string Text_PubKey {
            get {
                return ResourceManager.GetString("Text_PubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number: .
        /// </summary>
        internal static string Text_SerialNum {
            get {
                return ResourceManager.GetString("Text_SerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1 Digest: .
        /// </summary>
        internal static string Text_SHA1 {
            get {
                return ResourceManager.GetString("Text_SHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was signed with a certificate that has expired. If you acquired this file recently, it may not be authentic..
        /// </summary>
        internal static string Text_SigExpired {
            get {
                return ResourceManager.GetString("Text_SigExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature is invalid..
        /// </summary>
        internal static string Text_SigInvalid {
            get {
                return ResourceManager.GetString("Text_SigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been altered or corrupted since it was signed by the current user..
        /// </summary>
        internal static string Text_SigModified {
            get {
                return ResourceManager.GetString("Text_SigModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string Text_Signature {
            get {
                return ResourceManager.GetString("Text_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed by: .
        /// </summary>
        internal static string Text_Signer {
            get {
                return ResourceManager.GetString("Text_Signer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signer&apos;s identity is invalid..
        /// </summary>
        internal static string Text_SignerInvalid {
            get {
                return ResourceManager.GetString("Text_SignerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signer&apos;s identity is valid..
        /// </summary>
        internal static string Text_SignerValid {
            get {
                return ResourceManager.GetString("Text_SignerValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has not been modified since this signature was applied..
        /// </summary>
        internal static string Text_SigNoModified {
            get {
                return ResourceManager.GetString("Text_SigNoModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Time: .
        /// </summary>
        internal static string Text_SignTime {
            get {
                return ResourceManager.GetString("Text_SignTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature validity is unknown because it has not been included in your list of trusted certificates and none of its parent certificates are trusted certificates..
        /// </summary>
        internal static string Text_SigUnknown {
            get {
                return ResourceManager.GetString("Text_SigUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature is valid..
        /// </summary>
        internal static string Text_SigValid {
            get {
                return ResourceManager.GetString("Text_SigValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Authority Statement.
        /// </summary>
        internal static string Text_Statement {
            get {
                return ResourceManager.GetString("Text_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        internal static string Text_Status {
            get {
                return ResourceManager.GetString("Text_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject: .
        /// </summary>
        internal static string Text_Subject {
            get {
                return ResourceManager.GetString("Text_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject‘s Key Identifier: .
        /// </summary>
        internal static string Text_SubjectID {
            get {
                return ResourceManager.GetString("Text_SubjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Text_Summary {
            get {
                return ResourceManager.GetString("Text_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature validity is unknown because it has not been included in your list of trusted certificates and none of its parent certificates are trusted certificates..
        /// </summary>
        internal static string Text_Unknow {
            get {
                return ResourceManager.GetString("Text_Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Signature, .
        /// </summary>
        internal static string Text_Unknown {
            get {
                return ResourceManager.GetString("Text_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended Usage: .
        /// </summary>
        internal static string Text_Usage {
            get {
                return ResourceManager.GetString("Text_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Signature, .
        /// </summary>
        internal static string Text_Valid {
            get {
                return ResourceManager.GetString("Text_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from: .
        /// </summary>
        internal static string Text_ValidFrom {
            get {
                return ResourceManager.GetString("Text_ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid to: .
        /// </summary>
        internal static string Text_ValidTo {
            get {
                return ResourceManager.GetString("Text_ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string Text_Version {
            get {
                return ResourceManager.GetString("Text_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a digital ID file. Digital ID cards are password-protected. If you do not know the password, you cannot obtain a digital ID card..
        /// </summary>
        internal static string Text_ViewIDFile {
            get {
                return ResourceManager.GetString("Text_ViewIDFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Text_Warning {
            get {
                return ResourceManager.GetString("Text_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.509 Data: .
        /// </summary>
        internal static string Text_X509 {
            get {
                return ResourceManager.GetString("Text_X509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse a digital ID file. Digital ID cards are password-protected. If you do not know the password, you cannot obtain a digital ID card..
        /// </summary>
        internal static string Tip_AddID {
            get {
                return ResourceManager.GetString("Tip_AddID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate file.
        /// </summary>
        internal static string Tip_Cert {
            get {
                return ResourceManager.GetString("Tip_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the Password.
        /// </summary>
        internal static string Tip_Confirm {
            get {
                return ResourceManager.GetString("Tip_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Region.
        /// </summary>
        internal static string Tip_Country {
            get {
                return ResourceManager.GetString("Tip_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Tip_Date {
            get {
                return ResourceManager.GetString("Tip_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguishable name.
        /// </summary>
        internal static string Tip_DN {
            get {
                return ResourceManager.GetString("Tip_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Tip_DrawCancel {
            get {
                return ResourceManager.GetString("Tip_DrawCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Tip_DrawClear {
            get {
                return ResourceManager.GetString("Tip_DrawClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Tip_DrawOK {
            get {
                return ResourceManager.GetString("Tip_DrawOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Tip_Email {
            get {
                return ResourceManager.GetString("Tip_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A digital ID is required to create a digital signature. The most secure Digital ID is issued by trusted Certificate authorities and is based on secure devices like smart cards or tokens. Some are based on a file..
        /// </summary>
        internal static string Tip_ID {
            get {
                return ResourceManager.GetString("Tip_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital IDs that are self-signed by individuals do not provide the assurance that the identifying information is valid. For this reason, they may not be accepted in some cases..
        /// </summary>
        internal static string Tip_IDWarning {
            get {
                return ResourceManager.GetString("Tip_IDWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Text.
        /// </summary>
        internal static string Tip_Include {
            get {
                return ResourceManager.GetString("Tip_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Tip_Logo {
            get {
                return ResourceManager.GetString("Tip_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Tip_Name {
            get {
                return ResourceManager.GetString("Tip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new Digital ID, but they provide a low level of identity assurance..
        /// </summary>
        internal static string Tip_NewID {
            get {
                return ResourceManager.GetString("Tip_NewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        internal static string Tip_Organization {
            get {
                return ResourceManager.GetString("Tip_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Tip_Password {
            get {
                return ResourceManager.GetString("Tip_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string Tip_PasswordStatus {
            get {
                return ResourceManager.GetString("Tip_PasswordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Tip_Position {
            get {
                return ResourceManager.GetString("Tip_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Tip_Reason {
            get {
                return ResourceManager.GetString("Tip_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Location.
        /// </summary>
        internal static string Tip_Save {
            get {
                return ResourceManager.GetString("Tip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set A Password.
        /// </summary>
        internal static string Tip_SetPassword {
            get {
                return ResourceManager.GetString("Tip_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Tip_Sign {
            get {
                return ResourceManager.GetString("Tip_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string Tip_Tab {
            get {
                return ResourceManager.GetString("Tip_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Alignment.
        /// </summary>
        internal static string Tip_TextAlignment {
            get {
                return ResourceManager.GetString("Tip_TextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Certificate Is Trusted to:.
        /// </summary>
        internal static string Tip_TrustTo {
            get {
                return ResourceManager.GetString("Tip_TrustTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit.
        /// </summary>
        internal static string Tip_Unit {
            get {
                return ResourceManager.GetString("Tip_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Digital ID for.
        /// </summary>
        internal static string Tip_Use {
            get {
                return ResourceManager.GetString("Tip_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComPDFKit Version.
        /// </summary>
        internal static string Tip_Version {
            get {
                return ResourceManager.GetString("Tip_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Digital Signatures.
        /// </summary>
        internal static string Title_AddDigitalSign {
            get {
                return ResourceManager.GetString("Title_AddDigitalSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Digital ID.
        /// </summary>
        internal static string Title_AddID {
            get {
                return ResourceManager.GetString("Title_AddID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Viewer.
        /// </summary>
        internal static string Title_Cert {
            get {
                return ResourceManager.GetString("Title_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A Self-Signed Digital ID.
        /// </summary>
        internal static string Title_CreateID {
            get {
                return ResourceManager.GetString("Title_CreateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a type of Digital ID..
        /// </summary>
        internal static string Title_IDType {
            get {
                return ResourceManager.GetString("Title_IDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to File.
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the Self-Signed Digital ID to A File.
        /// </summary>
        internal static string Title_SaveSig {
            get {
                return ResourceManager.GetString("Title_SaveSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature Details.
        /// </summary>
        internal static string Title_Sig {
            get {
                return ResourceManager.GetString("Title_Sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Information.
        /// </summary>
        internal static string Title_SigInfo {
            get {
                return ResourceManager.GetString("Title_SigInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature List.
        /// </summary>
        internal static string Title_SigList {
            get {
                return ResourceManager.GetString("Title_SigList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the Signature Appearance.
        /// </summary>
        internal static string Title_SignAp {
            get {
                return ResourceManager.GetString("Title_SignAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust.
        /// </summary>
        internal static string Title_Trust {
            get {
                return ResourceManager.GetString("Title_Trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certify document.
        /// </summary>
        internal static string Trust_Cert {
            get {
                return ResourceManager.GetString("Trust_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign document or data.
        /// </summary>
        internal static string Trust_Sign {
            get {
                return ResourceManager.GetString("Trust_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Your Signature.
        /// </summary>
        internal static string Unknow_Draw {
            get {
                return ResourceManager.GetString("Unknow_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature, Non-Repudiation
        ///Encrypt Keys
        ///Encrypt Document
        ///Key Agreement
        ///Client Authentication
        ///Email Protection.
        /// </summary>
        internal static string Unknown_7 {
            get {
                return ResourceManager.GetString("Unknown_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Unknown_Label {
            get {
                return ResourceManager.GetString("Unknown_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Name.
        /// </summary>
        internal static string Unknown_Preset {
            get {
                return ResourceManager.GetString("Unknown_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Here!.
        /// </summary>
        internal static string Unknown_Tip1 {
            get {
                return ResourceManager.GetString("Unknown_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Name.
        /// </summary>
        internal static string Unknown_Tip2 {
            get {
                return ResourceManager.GetString("Unknown_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Your Signature.
        /// </summary>
        internal static string Unknown_Tip3 {
            get {
                return ResourceManager.GetString("Unknown_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Here!.
        /// </summary>
        internal static string Unknown_Tip5 {
            get {
                return ResourceManager.GetString("Unknown_Tip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign document or data
        ///Certify document
        ///Execute dynamic content that is embedded in a certified document
        ///Execute high privilege JavaScripts that are embedded in a certified document
        ///Perform privileged system operations (networking, printing, file access, etc.).
        /// </summary>
        internal static string Unknown_Tip6 {
            get {
                return ResourceManager.GetString("Unknown_Tip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Authentication.
        /// </summary>
        internal static string Usage_Client {
            get {
                return ResourceManager.GetString("Usage_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature.
        /// </summary>
        internal static string Usage_DigitalSignature {
            get {
                return ResourceManager.GetString("Usage_DigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt Document.
        /// </summary>
        internal static string Usage_Document {
            get {
                return ResourceManager.GetString("Usage_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Protection.
        /// </summary>
        internal static string Usage_Email {
            get {
                return ResourceManager.GetString("Usage_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Agreement.
        /// </summary>
        internal static string Usage_Key {
            get {
                return ResourceManager.GetString("Usage_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt Keys.
        /// </summary>
        internal static string Usage_Keys {
            get {
                return ResourceManager.GetString("Usage_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Repudiation.
        /// </summary>
        internal static string Usage_NonRepudiation {
            get {
                return ResourceManager.GetString("Usage_NonRepudiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid..
        /// </summary>
        internal static string Warn_Email {
            get {
                return ResourceManager.GetString("Warn_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string Warn_Name {
            get {
                return ResourceManager.GetString("Warn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file..
        /// </summary>
        internal static string Warn_NoFile {
            get {
                return ResourceManager.GetString("Warn_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        internal static string Warn_NoPassword {
            get {
                return ResourceManager.GetString("Warn_NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password does not match.
        /// </summary>
        internal static string Warn_Password {
            get {
                return ResourceManager.GetString("Warn_Password", resourceCulture);
            }
        }
    }
}
