//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compdfkit_Tools.Strings.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bota {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bota() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compdfkit_Tools.Strings.Bota", typeof(Bota).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Button_Done {
            get {
                return ResourceManager.GetString("Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark Title.
        /// </summary>
        internal static string Holder_BookmarkTitle {
            get {
                return ResourceManager.GetString("Holder_BookmarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Holder_Search {
            get {
                return ResourceManager.GetString("Holder_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Details.
        /// </summary>
        internal static string Menu_CertDetail {
            get {
                return ResourceManager.GetString("Menu_CertDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string Menu_DeleteAll {
            get {
                return ResourceManager.GetString("Menu_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Details.
        /// </summary>
        internal static string Menu_SigDetail {
            get {
                return ResourceManager.GetString("Menu_SigDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Annotations.
        /// </summary>
        internal static string Text_NoAnnotations {
            get {
                return ResourceManager.GetString("Text_NoAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bookmarks.
        /// </summary>
        internal static string Text_NoBookmarks {
            get {
                return ResourceManager.GetString("Text_NoBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Outlines.
        /// </summary>
        internal static string Text_NoOutline {
            get {
                return ResourceManager.GetString("Text_NoOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        internal static string Text_NoResult {
            get {
                return ResourceManager.GetString("Text_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Text_Page {
            get {
                return ResourceManager.GetString("Text_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results: .
        /// </summary>
        internal static string Text_Result {
            get {
                return ResourceManager.GetString("Text_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete it?.
        /// </summary>
        internal static string Text_SureDelete {
            get {
                return ResourceManager.GetString("Text_SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result found.
        /// </summary>
        internal static string Tip_Result {
            get {
                return ResourceManager.GetString("Tip_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string Title_Annot {
            get {
                return ResourceManager.GetString("Title_Annot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string Title_Bookmarks {
            get {
                return ResourceManager.GetString("Title_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlines.
        /// </summary>
        internal static string Title_Outlines {
            get {
                return ResourceManager.GetString("Title_Outlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature List.
        /// </summary>
        internal static string Title_Sig {
            get {
                return ResourceManager.GetString("Title_Sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        internal static string Title_Thumb {
            get {
                return ResourceManager.GetString("Title_Thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmarks.
        /// </summary>
        internal static string Tooltip_AddBookmarks {
            get {
                return ResourceManager.GetString("Tooltip_AddBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Annotations.
        /// </summary>
        internal static string Tooltip_Annot {
            get {
                return ResourceManager.GetString("Tooltip_Annot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Bookmarks.
        /// </summary>
        internal static string Tooltip_Bookmarks {
            get {
                return ResourceManager.GetString("Tooltip_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Tooltip_Delete {
            get {
                return ResourceManager.GetString("Tooltip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Tooltip_Edit {
            get {
                return ResourceManager.GetString("Tooltip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Annotations.
        /// </summary>
        internal static string Tooltip_Export {
            get {
                return ResourceManager.GetString("Tooltip_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Annotations.
        /// </summary>
        internal static string Tooltip_Import {
            get {
                return ResourceManager.GetString("Tooltip_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Outlines.
        /// </summary>
        internal static string Tooltip_Outlines {
            get {
                return ResourceManager.GetString("Tooltip_Outlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Tooltip_Search {
            get {
                return ResourceManager.GetString("Tooltip_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Signatures.
        /// </summary>
        internal static string Tooltip_Sig {
            get {
                return ResourceManager.GetString("Tooltip_Sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Thumbnails.
        /// </summary>
        internal static string Tooltip_Thumb {
            get {
                return ResourceManager.GetString("Tooltip_Thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warn_Warning {
            get {
                return ResourceManager.GetString("Warn_Warning", resourceCulture);
            }
        }
    }
}
