//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compdfkit_Tools.Strings.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolBar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compdfkit_Tools.Strings.ToolBar", typeof(ToolBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Button.
        /// </summary>
        internal static string Button_Btn {
            get {
                return ResourceManager.GetString("Button_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box.
        /// </summary>
        internal static string Button_Chb {
            get {
                return ResourceManager.GetString("Button_Chb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Button.
        /// </summary>
        internal static string Button_Cmb {
            get {
                return ResourceManager.GetString("Button_Cmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string Button_Extract {
            get {
                return ResourceManager.GetString("Button_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        internal static string Button_Image {
            get {
                return ResourceManager.GetString("Button_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Button_Insert {
            get {
                return ResourceManager.GetString("Button_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Box.
        /// </summary>
        internal static string Button_ListBox {
            get {
                return ResourceManager.GetString("Button_ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string Button_Merge {
            get {
                return ResourceManager.GetString("Button_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Signature Field.
        /// </summary>
        internal static string Button_NewSig {
            get {
                return ResourceManager.GetString("Button_NewSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Button_Paste {
            get {
                return ResourceManager.GetString("Button_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Button.
        /// </summary>
        internal static string Button_Rdo {
            get {
                return ResourceManager.GetString("Button_Rdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Button_Replace {
            get {
                return ResourceManager.GetString("Button_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string Button_Reverse {
            get {
                return ResourceManager.GetString("Button_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Button_Rotate {
            get {
                return ResourceManager.GetString("Button_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures.
        /// </summary>
        internal static string Button_Sig {
            get {
                return ResourceManager.GetString("Button_Sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string Button_Split {
            get {
                return ResourceManager.GetString("Button_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text.
        /// </summary>
        internal static string Button_Text {
            get {
                return ResourceManager.GetString("Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Field.
        /// </summary>
        internal static string Button_TextField {
            get {
                return ResourceManager.GetString("Button_TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the Signature.
        /// </summary>
        internal static string Button_VerifySig {
            get {
                return ResourceManager.GetString("Button_VerifySig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        internal static string Tooltip_Arrow {
            get {
                return ResourceManager.GetString("Tooltip_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Tooltip_Audio {
            get {
                return ResourceManager.GetString("Tooltip_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Tooltip_Circle {
            get {
                return ResourceManager.GetString("Tooltip_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink.
        /// </summary>
        internal static string Tooltip_Freehand {
            get {
                return ResourceManager.GetString("Tooltip_Freehand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeText.
        /// </summary>
        internal static string Tooltip_FreeText {
            get {
                return ResourceManager.GetString("Tooltip_FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Tooltip_Highlight {
            get {
                return ResourceManager.GetString("Tooltip_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Tooltip_Image {
            get {
                return ResourceManager.GetString("Tooltip_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Tooltip_Line {
            get {
                return ResourceManager.GetString("Tooltip_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Tooltip_Link {
            get {
                return ResourceManager.GetString("Tooltip_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Tooltip_Note {
            get {
                return ResourceManager.GetString("Tooltip_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures.
        /// </summary>
        internal static string Tooltip_Signature {
            get {
                return ResourceManager.GetString("Tooltip_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Tooltip_Square {
            get {
                return ResourceManager.GetString("Tooltip_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squiggly.
        /// </summary>
        internal static string Tooltip_Squiggly {
            get {
                return ResourceManager.GetString("Tooltip_Squiggly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        internal static string Tooltip_Stamp {
            get {
                return ResourceManager.GetString("Tooltip_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikeout.
        /// </summary>
        internal static string Tooltip_Strikeout {
            get {
                return ResourceManager.GetString("Tooltip_Strikeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Tooltip_Underline {
            get {
                return ResourceManager.GetString("Tooltip_Underline", resourceCulture);
            }
        }
    }
}
