//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFViewer.Strings.SettingDialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFViewer.Strings.SettingDialog", typeof(SettingDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ 2014-2023 PDF Technologies, Inc. All Rights Reserved..
        /// </summary>
        internal static string Link_CopyRight {
            get {
                return ResourceManager.GetString("Link_CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Link_Policy {
            get {
                return ResourceManager.GetString("Link_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Terms.
        /// </summary>
        internal static string Link_Service {
            get {
                return ResourceManager.GetString("Link_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Author.
        /// </summary>
        internal static string Setting_Author {
            get {
                return ResourceManager.GetString("Setting_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Ratio.
        /// </summary>
        internal static string Setting_Divisor {
            get {
                return ResourceManager.GetString("Setting_Divisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Form Fields.
        /// </summary>
        internal static string Setting_HighlightForms {
            get {
                return ResourceManager.GetString("Setting_HighlightForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Links.
        /// </summary>
        internal static string Setting_HighlightLinks {
            get {
                return ResourceManager.GetString("Setting_HighlightLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ComPDFKit.
        /// </summary>
        internal static string Subtitle_About {
            get {
                return ResourceManager.GetString("Subtitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Subtitle_Email {
            get {
                return ResourceManager.GetString("Subtitle_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Sales.
        /// </summary>
        internal static string Subtitle_Sales {
            get {
                return ResourceManager.GetString("Subtitle_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        internal static string Subtitle_Support {
            get {
                return ResourceManager.GetString("Subtitle_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Subtitle_Version {
            get {
                return ResourceManager.GetString("Subtitle_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Subtitle_Website {
            get {
                return ResourceManager.GetString("Subtitle_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the application to apply the language change. Do you want to restart now?.
        /// </summary>
        internal static string Tip_Restart {
            get {
                return ResourceManager.GetString("Tip_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Application.
        /// </summary>
        internal static string Tip_RestartTitle {
            get {
                return ResourceManager.GetString("Tip_RestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        internal static string Title_CompanyInfo {
            get {
                return ResourceManager.GetString("Title_CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Title_GlobalSettings {
            get {
                return ResourceManager.GetString("Title_GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK Information.
        /// </summary>
        internal static string Title_SDKInfo {
            get {
                return ResourceManager.GetString("Title_SDKInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
    }
}
